




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;	     

namespace SocialGameS2C
{
	internal class Stub:Nettention.Proud.RmiStub
	{
public AfterRmiInvocationDelegate AfterRmiInvocation = delegate(Nettention.Proud.AfterRmiSummary summary) {};
public BeforeRmiInvocationDelegate BeforeRmiInvocation = delegate(Nettention.Proud.BeforeRmiSummary summary) {};

		public delegate bool ReplyLogonDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int groupID, int result, String comment, bool isMaster);  
		public ReplyLogonDelegate ReplyLogon = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int groupID, int result, String comment, bool isMaster)
		{ 
			return false;
		};
		public delegate bool NotifyAddTreeDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int groupID, int treeID, UnityEngine.Vector3 position);  
		public NotifyAddTreeDelegate NotifyAddTree = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int groupID, int treeID, UnityEngine.Vector3 position)
		{ 
			return false;
		};
		public delegate bool NotifyRemoveTreeDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int groupID, int treeID);  
		public NotifyRemoveTreeDelegate NotifyRemoveTree = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int groupID, int treeID)
		{ 
			return false;
		};
		public delegate bool NotifyPlayerJoinDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int groupID, String nick, int idx);  
		public NotifyPlayerJoinDelegate NotifyPlayerJoin = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int groupID, String nick, int idx)
		{ 
			return false;
		};
		public delegate bool NotifyPlayerLeaveDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int groupID, int idx, bool changeMaster, int newMasterID);  
		public NotifyPlayerLeaveDelegate NotifyPlayerLeave = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int groupID, int idx, bool changeMaster, int newMasterID)
		{ 
			return false;
		};
	public override bool ProcessReceivedMessage(Nettention.Proud.ReceivedMessage pa, Object hostTag) 
	{
		Nettention.Proud.HostID remote=pa.RemoteHostID;
		if(remote==Nettention.Proud.HostID.HostID_None)
		{
			ShowUnknownHostIDWarning(remote);
		}

		Nettention.Proud.Message __msg=pa.ReadOnlyMessage;
		int orgReadOffset = __msg.ReadOffset;
        Nettention.Proud.RmiID __rmiID = Nettention.Proud.RmiID.RmiID_None;
        if (!__msg.Read( out __rmiID))
            goto __fail;
					
		switch(__rmiID)
		{
        case Common.ReplyLogon:
            ProcessReceivedMessage_ReplyLogon(__msg, pa, hostTag, remote);
            break;
        case Common.NotifyAddTree:
            ProcessReceivedMessage_NotifyAddTree(__msg, pa, hostTag, remote);
            break;
        case Common.NotifyRemoveTree:
            ProcessReceivedMessage_NotifyRemoveTree(__msg, pa, hostTag, remote);
            break;
        case Common.NotifyPlayerJoin:
            ProcessReceivedMessage_NotifyPlayerJoin(__msg, pa, hostTag, remote);
            break;
        case Common.NotifyPlayerLeave:
            ProcessReceivedMessage_NotifyPlayerLeave(__msg, pa, hostTag, remote);
            break;
		default:
			 goto __fail;
		}
		return true;
__fail:
	  {
			__msg.ReadOffset = orgReadOffset;
			return false;
	  }
	}
    void ProcessReceivedMessage_ReplyLogon(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int groupID; SngClient.Marshaler.Read(__msg,out groupID);	
int result; SngClient.Marshaler.Read(__msg,out result);	
String comment; SngClient.Marshaler.Read(__msg,out comment);	
bool isMaster; SngClient.Marshaler.Read(__msg,out isMaster);	
core.PostCheckReadMessage(__msg, RmiName_ReplyLogon);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=groupID.ToString()+",";
parameterString+=result.ToString()+",";
parameterString+=comment.ToString()+",";
parameterString+=isMaster.ToString()+",";
        NotifyCallFromStub(Common.ReplyLogon, RmiName_ReplyLogon,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.ReplyLogon;
        summary.rmiName = RmiName_ReplyLogon;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =ReplyLogon (remote,ctx , groupID, result, comment, isMaster );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_ReplyLogon);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.ReplyLogon;
        summary.rmiName = RmiName_ReplyLogon;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_NotifyAddTree(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int groupID; SngClient.Marshaler.Read(__msg,out groupID);	
int treeID; SngClient.Marshaler.Read(__msg,out treeID);	
UnityEngine.Vector3 position; SngClient.Marshaler.Read(__msg,out position);	
core.PostCheckReadMessage(__msg, RmiName_NotifyAddTree);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=groupID.ToString()+",";
parameterString+=treeID.ToString()+",";
parameterString+=position.ToString()+",";
        NotifyCallFromStub(Common.NotifyAddTree, RmiName_NotifyAddTree,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.NotifyAddTree;
        summary.rmiName = RmiName_NotifyAddTree;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =NotifyAddTree (remote,ctx , groupID, treeID, position );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_NotifyAddTree);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.NotifyAddTree;
        summary.rmiName = RmiName_NotifyAddTree;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_NotifyRemoveTree(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int groupID; SngClient.Marshaler.Read(__msg,out groupID);	
int treeID; SngClient.Marshaler.Read(__msg,out treeID);	
core.PostCheckReadMessage(__msg, RmiName_NotifyRemoveTree);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=groupID.ToString()+",";
parameterString+=treeID.ToString()+",";
        NotifyCallFromStub(Common.NotifyRemoveTree, RmiName_NotifyRemoveTree,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.NotifyRemoveTree;
        summary.rmiName = RmiName_NotifyRemoveTree;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =NotifyRemoveTree (remote,ctx , groupID, treeID );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_NotifyRemoveTree);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.NotifyRemoveTree;
        summary.rmiName = RmiName_NotifyRemoveTree;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_NotifyPlayerJoin(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int groupID; SngClient.Marshaler.Read(__msg,out groupID);	
String nick; SngClient.Marshaler.Read(__msg,out nick);	
int idx; SngClient.Marshaler.Read(__msg,out idx);	
core.PostCheckReadMessage(__msg, RmiName_NotifyPlayerJoin);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=groupID.ToString()+",";
parameterString+=nick.ToString()+",";
parameterString+=idx.ToString()+",";
        NotifyCallFromStub(Common.NotifyPlayerJoin, RmiName_NotifyPlayerJoin,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.NotifyPlayerJoin;
        summary.rmiName = RmiName_NotifyPlayerJoin;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =NotifyPlayerJoin (remote,ctx , groupID, nick, idx );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_NotifyPlayerJoin);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.NotifyPlayerJoin;
        summary.rmiName = RmiName_NotifyPlayerJoin;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_NotifyPlayerLeave(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int groupID; SngClient.Marshaler.Read(__msg,out groupID);	
int idx; SngClient.Marshaler.Read(__msg,out idx);	
bool changeMaster; SngClient.Marshaler.Read(__msg,out changeMaster);	
int newMasterID; SngClient.Marshaler.Read(__msg,out newMasterID);	
core.PostCheckReadMessage(__msg, RmiName_NotifyPlayerLeave);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=groupID.ToString()+",";
parameterString+=idx.ToString()+",";
parameterString+=changeMaster.ToString()+",";
parameterString+=newMasterID.ToString()+",";
        NotifyCallFromStub(Common.NotifyPlayerLeave, RmiName_NotifyPlayerLeave,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.NotifyPlayerLeave;
        summary.rmiName = RmiName_NotifyPlayerLeave;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =NotifyPlayerLeave (remote,ctx , groupID, idx, changeMaster, newMasterID );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_NotifyPlayerLeave);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.NotifyPlayerLeave;
        summary.rmiName = RmiName_NotifyPlayerLeave;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_ReplyLogon="ReplyLogon";
public const string RmiName_NotifyAddTree="NotifyAddTree";
public const string RmiName_NotifyRemoveTree="NotifyRemoveTree";
public const string RmiName_NotifyPlayerJoin="NotifyPlayerJoin";
public const string RmiName_NotifyPlayerLeave="NotifyPlayerLeave";
       
public const string RmiName_First = RmiName_ReplyLogon;
#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_ReplyLogon="";
public const string RmiName_NotifyAddTree="";
public const string RmiName_NotifyRemoveTree="";
public const string RmiName_NotifyPlayerJoin="";
public const string RmiName_NotifyPlayerLeave="";
       
public const string RmiName_First = "";
#endif
		public override Nettention.Proud.RmiID[] GetRmiIDList { get{return Common.RmiIDList;} }
		
	}
}

